apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: mohamedmahmoud94/myjenkins:V2

          ports:
            - name: jenkins-port
              containerPort: 8080
            - name: unknown-port
              containerPort: 50000

          volumeMounts:
            - name: jenkins
              mountPath: /var/jenkins_home
            
            - name: kubernetes
              mountPath: /usr/bin/kubectl
              subPath: kubectl
            
            - name: docker
              mountPath: /usr/bin/docker
              subPath: docker
            
            - name: dockersock
              mountPath: /var/run/docker.sock
      
       initContainers:
         - name: init-docker
           image: docker
           command: ["cp","/usr/local/bin/docker", "/opt/temp"]    
            
           volumeMounts:  
             - name: docker
               mountPath: /opt/temp
 
         - name: init-k8s
           image: alpine/k8s:1.23.13
           command: ["cp","/usr/bin/kubectl", "/opt/temp"]

           volumeMounts:
             - name: kubernetes
               mountPath: "/opt/temp"
        
      volumes:
        - name: jenkins
          persistentVolumeClaim:
            claimName: jenkins-claim

        - name: kubernetes
          emptyDir: {}

        - name: docker
           emptyDir: {}
        
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
    - name: http
      port: 80
      targetPort: 8080
    - name: slave
      port: 50000
      protocol: TCP
  selector:
    app: jenkins
