pipeline {
    agent any


    stages {
        stage('ci') {
            steps {
             withCredentials([usernamePassword(credentialsId: 'github', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]){

                // Get some code from a GitHub repository
                git 'https://github.com/MohamedEl-Sayed28/bakehouse-ITI'}

                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]){
                sh "docker build . -t ${USERNAME}/minya:v2 -f Dockerfile"
                sh "docker login -u ${USERNAME} -p ${PASSWORD}"
                sh "docker push ${USERNAME}/minya:v2"}


                
            }


        }
        stage('cd'){
            steps{
                  sh """
                  kubectl apply -f deploy.yaml 
                  kubectl apply -f service.yaml 
                  """

            }

        }
    }
}
